name: Backend app docker image build and manifest update

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACTION_TOKEN }}

    - name: Build Docker image
      run: |
        cd backend
        docker build -t ghcr.io/anonymous-peasant/backend-spring-boot-app .

    # name: Test Docker image
    #   run: |
    #     docker run --rm ghcr.io/anonymous-peasant/backend-spring-boot-app echo "Tests passed"

    - name: Push Docker image
      run: |
        docker tag ghcr.io/anonymous-peasant/backend-spring-boot-app:latest ghcr.io/anonymous-peasant/backend-spring-boot-app:${{ github.sha }}
        docker push ghcr.io/anonymous-peasant/backend-spring-boot-app:${{ github.sha }}

  update-backend-manifest:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Clone manifest repository
      run: |
        git clone https://github.com/anonymous-peasant/nus-iss-devsecops-2024-project-deploy.git

    - name: Commit and push changes
      run: |
        echo "Replacing tag with SHA: ${{ github.sha }}"
        sed -i "s/image:.*/image: ghcr.io\/nus-iss-devsecops-2024-project-app:backend-spring-boot-app\/${{ github.sha }}/" ./nus-iss-devsecops-2024-project-deploy/backend/deployment.yaml
        cd ./nus-iss-devsecops-2024-project-deploy
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        echo "Committing the changes..."
        git commit -m "Update manifest with new Docker tag: ${{ github.sha }}"
        echo "Setting up remote URL with access token..."
        git remote set-url origin https://anonymous-peasant:${{ secrets.ACTION_TOKEN }}@github.com/anonymous-peasant/nus-iss-devsecops-2024-project-deploy.git
        echo "Pushing to origin/main..."
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
